// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartMed.Infrastructure;

#nullable disable

namespace SmartMed.Migrations
{
    [DbContext(typeof(MedicationDbContext))]
    [Migration("20220429214520_Medications table")]
    partial class Medicationstable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SmartMed.Model.Medication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("Medications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2022, 4, 29, 22, 45, 20, 686, DateTimeKind.Local).AddTicks(5671),
                            Name = "Ibuprofeno",
                            Quantity = 3,
                            UniqueId = new Guid("040f6c87-46f3-4273-a074-c7c263df3795")
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2022, 4, 29, 22, 45, 20, 686, DateTimeKind.Local).AddTicks(5720),
                            Name = "Paracetemol",
                            Quantity = 5,
                            UniqueId = new Guid("416e39ba-f610-4bc9-8aae-01cc676868fd")
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2022, 4, 29, 22, 45, 20, 686, DateTimeKind.Local).AddTicks(5724),
                            Name = "Aspirina",
                            Quantity = 2,
                            UniqueId = new Guid("52bcc397-5936-417a-88d1-695807bc9524")
                        },
                        new
                        {
                            Id = 4,
                            CreationDate = new DateTime(2022, 4, 29, 22, 45, 20, 686, DateTimeKind.Local).AddTicks(5727),
                            Name = "Tramadol",
                            Quantity = 1,
                            UniqueId = new Guid("4c90a9e0-b18c-4049-8bcc-b59c54fe70e9")
                        },
                        new
                        {
                            Id = 5,
                            CreationDate = new DateTime(2022, 4, 29, 22, 45, 20, 686, DateTimeKind.Local).AddTicks(5730),
                            Name = "Codeína",
                            Quantity = 10,
                            UniqueId = new Guid("d8aa141f-84f7-474d-92f0-c5eebdea8606")
                        },
                        new
                        {
                            Id = 6,
                            CreationDate = new DateTime(2022, 4, 29, 22, 45, 20, 686, DateTimeKind.Local).AddTicks(5733),
                            Name = "Metamizol",
                            Quantity = 5,
                            UniqueId = new Guid("33b35c53-2620-4756-bab9-3b390df80069")
                        },
                        new
                        {
                            Id = 7,
                            CreationDate = new DateTime(2022, 4, 29, 22, 45, 20, 686, DateTimeKind.Local).AddTicks(5736),
                            Name = "Gabapentina",
                            Quantity = 3,
                            UniqueId = new Guid("7fc471ac-b16a-4166-90a1-ff13a56a47df")
                        },
                        new
                        {
                            Id = 8,
                            CreationDate = new DateTime(2022, 4, 29, 22, 45, 20, 686, DateTimeKind.Local).AddTicks(5739),
                            Name = "Daflon",
                            Quantity = 20,
                            UniqueId = new Guid("efdab810-1d77-4906-9464-05475d7231a5")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
